LibraryApp/Areas/Student/Controllers/CompletedController.cs
using System.Web;
using System.Web.Mvc;
using LibraryBILayer.User;
using System.Collections.Generic;
using LibraryBILayer.Comman;

namespace LibraryApp.Areas.NewAdmin.Controllers
{
    public class CompletedController : Controller
    {           
        public ActionResult Index()
        {
            HttpCookie objadmprof = Request.Cookies["User"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("~/Areas/Student/Views/Profile/Index.cshtml");
        }

        public ActionResult CompletedAssignment()
        {

            HttpCookie objadmprof = Request.Cookies["User"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Home");
            }
            CompletedAssignments CompletedAssignments = new CompletedAssignments();
            string studentid = objadmprof.Value;
            var id = studentid.Split('&');
            string Id = id[3].Replace("StudID=", "");
            List<JoinClassForPCR> result = CompletedAssignments.getCompletedAssignment(Id);

            return View(result);
        }

        public ActionResult CompletedresultById(int id)
        {
            HttpCookie objadmprof = Request.Cookies["User"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Home");
            }
            CompletedAssignments CompletedAssignments = new CompletedAssignments();
            string studentid = objadmprof.Value;
            var id1 = studentid.Split('&');
            string StudId = id1[3].Replace("StudID=", "");
            JoinClassForPCR result = CompletedAssignments.getCompletedAssignmentbyId(StudId,id);
            return View(result);
        }
    
    }
}

LibraryApp/Areas/Student/Views/Completed/CompletedAssignment.cshtml
@model IEnumerable<LibraryBILayer.Comman.JoinClassForPCR>

@{
    ViewBag.Title = "CompletedAssignment";
    Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";
}

<script src="~/Contents/customjs/jquery.validate.min.js"></script>
<script src="~/Contents/customjs/jquery.validate.unobtrusive.js"></script>
<script src="~/Contents/customjs/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Contents/customcss/validate.css" rel="stylesheet" />
<script src="~/Contents/customjs/validations.js"></script>

<style>
    .pagination {
        float: right;
        margin: 0;
    }

        .pagination li.active a {
            cursor: not-allowed;
        }

            .pagination li.active a:hover {
                cursor: not-allowed;
            }

    .fa-sort {
        margin: 0 4px;
    }

    .faSpinner {
        display: none;
        position: absolute;
        z-index: 9;
        width: 100%;
        height: 100%;
        background: #ddd;
        opacity: 0.4;
    }

        .faSpinner i {
            position: absolute;
            left: 40%;
            top: 40%;
        }

    .myWd {
        width: 60%;
    }
</style>

<div class="content-wrapper" style="min-height: 960px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            History
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Student/Profile/StudentProfile"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">View History</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> History List</h3>


                    </div><!-- /.box-header -->
                    <div class="box-body" id="ArticlesList">
                        @if (Model != null)
                        {
                            <table class="table table-bordered table-striped" style="background-color:white">
                                <thead>
                                    <tr>
                                        <th width="20%">Service</th>
                                        <th width="20%">Subject</th>
                                        <th width="20%">Question</th>
                                        <th width="20%">Price</th>
                                        <th width="20%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@item.ServiceType</td>
                                        <td>@item.Subject</td>
                                        <td>@item.Question</td>
                                        @if (@item.Price == null)
                                        {
                                            <td>$ 0.00</td>
                                        }
                                        else
                                        {
                                            <td>$ @item.Price</td>
                                        }

                                        <td> @Html.ActionLink("View", "CompletedresultById", "Completed", new { @area = "Student", @id = item.id }, new { @class = "btn btn-primary btn-xs" })</td>

                                    </tr>
                                    }
                                </tbody>

                            </table>
                        }
                        else
                        {
                            <span style="color:rosybrown"><strong>No record found!!</strong></span>
                        }
                    </div><!-- /.box-body -->
                </div>
                <!-- /.box-footer -->

            </div><!-- /.col -->
        </div>

    </section><!-- /.content -->
</div>


<script src="~/Areas/NewAdmin/NewContent/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script src="~/Areas/NewAdmin/NewContent/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.4/tinymce.min.js"></script>

LibraryApp/Areas/Student/Views/Completed/CompletedresultById.cshtml
@{
    ViewBag.Title = "Completed Assignment";
    Layout = "~/Areas/Student/Views/Shared/_Layout.cshtml";
}
@model LibraryBILayer.Comman.JoinClassForPCR

<script src="~/Contents/customjs/jquery.validate.min.js"></script>
<script src="~/Contents/customjs/jquery.validate.unobtrusive.js"></script>
<script src="~/Contents/customjs/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Contents/customcss/validate.css" rel="stylesheet" />
<script src="~/Contents/customjs/validations.js"></script>


<style>
    .custom-input-error {
        border: 1px solid #a94442 !important;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075) !important;
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075) !important;
        background-color: #FBE8E8 !important;
    }

    .custom-input-success {
        border: 1px solid #3c763d !important;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075) !important;
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075) !important;
        background-color: #D6F3D6 !important;
    }

    .add_field_button {
        background-color: #089cd3;
        border: none;
        margin-bottom: 15px;
        color: #fff;
        font-weight: 400;
        padding: 5px 11px;
    }

    .add_field_button1 {
        background-color: #089cd3;
        border: none;
        margin-bottom: 15px;
        color: #fff;
        font-weight: 400;
        padding: 5px 11px;
    }
</style>

<div class="content-wrapper" style="min-height: 960px;">

    <section class="content-header">
        <h1>
            Detail
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Student/Profile/StudentProfile"><i class="fa fa-dashboard"></i> Home</a></li>

        </ol>
    </section>
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Details</h3>

                    </div><!-- /.box-header -->
                    <div class="box-body">

                        <div class="form-group">
                            <label for="exampleInputEmail1">Service</label>
                            @Html.DisplayFor(model => Model.ServiceType, new { @class = "form-control" })
                            @*  @Html.DropDownListFor(m => m.UID, (IEnumerable<SelectListItem>)ViewBag.University, "Select", new { @class = "form-control", style = "width:85%" })*@
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Subject</label>
                            @Html.DisplayFor(model => Model.Subject, new { @class = "form-control" })
                            @*  @Html.DropDownListFor(m => m.UID, (IEnumerable<SelectListItem>)ViewBag.University, "Select", new { @class = "form-control", style = "width:85%" })*@
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Question</label>
                            @Html.DisplayFor(model => Model.Question, new { @class = "form-control" })
                            @*  @Html.DropDownListFor(m => m.UID, (IEnumerable<SelectListItem>)ViewBag.University, "Select", new { @class = "form-control", style = "width:85%" })*@
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Price</label>
                            @if (Model.Price == null)
                            {
                                Model.Price = 0.00m;
                            }
                            @Html.DisplayFor(model => Model.Price, new { @class = "form-control" })
                            @*  @Html.DropDownListFor(m => m.UID, (IEnumerable<SelectListItem>)ViewBag.University, "Select", new { @class = "form-control", style = "width:85%" })*@
                        </div>

                    </div><!-- ./box-body -->
                    <!-- /.box-footer -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div>

    </section><!-- /.content -->
</div>

<script src="~/Areas/NewAdmin/NewContent/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script src="~/Areas/NewAdmin/NewContent/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.4/tinymce.min.js"></script>