LibraryApp/Areas/NewAdmin/Controllers/ManageCDRServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryBILayer.Admin;
using PagedList;
using LibraryDataLayer;
using LibraryUtility;

namespace LibraryApp.Areas.NewAdmin.Controllers
{
    public class ManageCDRServiceController : Controller
    {
        // GET: NewAdmin/Question
        public ActionResult Index()
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Panel");
            }
            int pageNo = 1;
            int pageSize = 100;
            var GetList = ManageLibrary.QuestionList((Int32)Enums.ServiceTypeID.CDRServices);
            ViewBag.data = GetList.ToPagedList(pageNo, pageSize);
            ViewBag.TotalCount = GetList.Count;
            ViewBag.pageSize = pageSize;
            ViewBag.IsDeleted = false;
            ViewBag.Page = pageNo;
            return View();
        }
        public ActionResult CDRServicesList(int page = 1)
        {
            int pageSize = 100;
            List<QuestionLib> objQuestion = new List<QuestionLib>();
            //  bool IsDeleted = Convert.ToBoolean(IsActive);
            objQuestion = ManageLibrary.QuestionList((Int32)Enums.ServiceTypeID.CDRServices);

            ViewData["TotalQuestionCount"] = objQuestion.Count;
            ViewBag.Page = page;
            ViewBag.pageSize = pageSize;
            //ViewBag.IsDeleted = IsActive;
            return Request.IsAjaxRequest()
                             ? (ActionResult)PartialView("CDRServicesList", objQuestion.ToPagedList(page, pageSize))
                             : PartialView("CDRServicesList", objQuestion.ToPagedList(page, pageSize));

        }
        public ActionResult ViewQuestion(int Id)
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Panel");
            }

            var data = ManageLibrary.ViewCDRServiceByID(Id);
            return View(data);
        }

        [HttpPost]
        public ActionResult UpdateStatus(QuestionLib model)
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Panel");
            }

            if (model.ChangeStatusID > 0)
            {
                model.StatusID = model.ChangeStatusID;
            }
            var data = ManageLibrary.UpdateQuestionID(model.ID, model.StatusID, model.EstimatedPrice);
            return RedirectToAction("Index");
        }        
    }
}

LibraryApp/Areas/NewAdmin/Views/ManageCDRService/CDRServicesList.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<LibraryBILayer.Admin.QuestionLib>

@{
    var totalCount = Convert.ToInt32(ViewData["TotalArticleCount"]);
}
@if (Model.Count > 0 && Model != null)
{
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th width="10%">Created On</th>
                <th width="15%">Student Name</th>             
                <th width="15%">Subject</th>
                <th width="15%">Message</th>
                <th width="15%">Payment Status</th>
                <th width="15%">Assignment Status</th>
                <th width="15%">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Convert.ToDateTime(item.CreatedOn).ToString("yyyy-MM-dd")</td>
                <td>@item.Name</td>
                <td>@item.Subject</td>
                <td>@item.Question</td>

                <td>@item.PaymentStatus</td>
                <td>@item.Status</td>
                <td>
                    <a title="View" href="@Url.Action("ViewQuestion", "ManageCDRService", new { @area = "NewAdmin", @Id = item.ID })"><i class="fa  fa-eye fa-2x"></i></a>


                </td>
            </tr>
            }
        </tbody>

    </table>
    if (totalCount > ViewBag.pageSize)
    {
        @Html.PagedListPager(Model, page => Url.Action("CDRServicesList", "ManageCDRService", new { area = "NewAdmin",  page }));
    }
}
else
{
    <span style="color:rosybrown"><strong>No record found!!</strong></span>
}

LibraryApp/Areas/NewAdmin/Views/ManageCDRService/Index.cshtml
@using PagedList;
@using PagedList.Mvc
@{
    ViewBag.Title = "CDR Service List";
    Layout = "~/Areas/NewAdmin/Views/Shared/_Layout.cshtml";
    var data = (PagedList<LibraryBILayer.Admin.QuestionLib>)ViewBag.data;
}

<style>
    .pagination {
        float: right;
        margin: 0;
    }

        .pagination li.active a {
            cursor: not-allowed;
        }

            .pagination li.active a:hover {
                cursor: not-allowed;
            }

    .fa-sort {
        margin: 0 4px;
    }

    .faSpinner {
        display: none;
        position: absolute;
        z-index: 9;
        width: 100%;
        height: 100%;
        background: #ddd;
        opacity: 0.4;
    }

        .faSpinner i {
            position: absolute;
            left: 40%;
            top: 40%;
        }

    .myWd {
        width: 60%;
    }
</style>

<div class="content-wrapper" style="min-height: 960px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            CDR Services List
            @*<div class="topAddNewLink"><a href="/NewAdmin/SolutionLibrary/AddSolution" class="btn btn-primary btn-xs">Add New</a></div>*@
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Admin/Dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">View  CDR Services List</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">CDR Services</h3>

                        @*<a href="javascript:void(0)" class="btn btn-primary" onclick="window.history.back();" style="float: right;">Back</a>*@
                        @*<div class="checkbox">
                                <label>
                                    <input style="float:right" type="checkbox" id="InActive" onchange="GetArticlesList(this);" class="minimal"> In-Active
                                </label>
                            </div>*@
                        @*<div class="box-tools pull-right">
                                <div class="has-feedback">
                                    <input type="text" id="Search" class="form-control input-sm" placeholder="Search - Solution Library" style="width:300px" />
                                    <span class="glyphicon glyphicon-search form-control-feedback"></span>
                                </div>
                            </div>*@
                    </div><!-- /.box-header -->
                    <div class="box-body" id="ArticlesList">
                        @{
                            ViewDataDictionary extraData = new ViewDataDictionary(ViewData) { { "TotalArticleCount", ViewBag.TotalCount } };
                            Html.RenderPartial("CDRServicesList", data, extraData);
                        }

                    </div><!-- /.box-body -->
                </div>
                <!-- /.box-footer -->

            </div><!-- /.col -->
        </div>

    </section><!-- /.content -->
</div>

@*<script type="text/javascript">
        function DeleteRecord(Id, status) {
            var txt;
            var r = confirm("Do you really want to perform this action?");
            if (r == true) {
                $.ajax({
                    url: '@Url.Action("DeleteSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                    type: "POST",
                    data: JSON.stringify({ Id: Id, status: status }),
                    async: false,
                    contentType: "application/json",
                    dataType: "json",
                    success: function (result) {
                        if (result > 0) {
                            if (status == "0") {
                                toastr["success"]("Record is successfully deactivated.");
                            }
                            else if (status == "4") {
                                toastr["success"]("Record is successfully deleted.");
                            }
                            else {
                                toastr["success"]("Record is successfully activated.");
                            }
                            //  alert("Record is successfully deleted.");
                            GetArticlesList();
                        }
                        else {
                            toastr["error"]("Some error while processing your request.")
                        }
                    },
                    error: function (data) {
                        toastr["error"]("Some error while processing your request.")
                    }
                });
            }
            else {
                txt = "You pressed Cancel!";
            }
        }

        function FinalDelete(Id, status) {
            var txt;
            var r = confirm("Do you really want to perform this action?");
            if (r == true) {
                $.ajax({
                    url: '@Url.Action("FinalDeleteSolution", "SolutionLibrary", new { area = "NewAdmin" })',
                    type: "POST",
                    data: JSON.stringify({ Id: Id, status: status }),
                    async: false,
                    contentType: "application/json",
                    dataType: "json",
                    success: function (result) {
                        if (result > 0) {
                            toastr["success"]("Record is successfully deleted.");
                            //  alert("Record is successfully deleted.");
                            GetArticlesList();
                        }
                        else {
                            toastr["error"]("Some error while processing your request.")
                        }
                    },
                    error: function (data) {
                        toastr["error"]("Some error while processing your request.")
                    }
                });
            }
            else {
                txt = "You pressed Cancel!";
            }
        }
    </script>
    <script type="text/javascript">
        $('#Search').keyup(function () {
              var Search = $('#Search').val().replace(/[/\<>]/g, '');
            if ($('#Search').val().length > 2) {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                    data: { SearchStr: Search, IsActive: 1 },
                    success: function (data) {

                        if (data != 0) {
                            $('#ArticlesList').html(data)
                        }
                        else {
                            alert("No Record Found!!");
                        }
                    },
                    error: function (data) {
                    }
                });
            }
            else {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                    data: { SearchStr: "", IsActive: 1 },
                    success: function (data) {

                        if (data != 0) {
                            $('#ArticlesList').html(data)
                        }
                        else {
                            alert("No Record Found!!");
                        }
                    },
                    error: function (data) {
                    }
                });
            }
        });

    </script>*@
<script>
    function GetArticlesList(elem) {
        $(elem).attr("disabled", 1);
        var HTML = "";
        var chkdata = "";
        var IsActive = $('#InActive').is(":Checked");
        if (IsActive == true)
        {
            chkdata = 0;
        }
        else
        {
            chkdata = 1;
        }
        $.ajax({
            type: 'GET',
            async: false,
            url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { @area = "NewAdmin" })',
            data: { IsActive: chkdata },
            success: function (data) {
                if (data != null) {
                    $('#ArticlesList').html(data)

                    $(elem).removeAttr("disabled");
                }
                else {
                    alert("No Record Found!!")
                }
            },
            error: function (response) {
            }
        });
    }

   // $('body').on('click', '#ArticlesList a', function (event) {
   //     if (!$(this).hasClass('btn-xs')) {
   //         var url = $(this).attr("href");
   //         var HTML = "";
   //         var InActive = $('#InActive').is(":Checked");
   //         $(".faSpinner").show();
   //         //alert("welcome home");
   //         if (url != undefined) {
   //             event.preventDefault();

   //             url = url + '&IsActive=' + $('#InActive').is(":Checked").toString();
   //             setTimeout(function () {
   //                 $.ajax({
   //                     url: url,
   //                     success: function (result) {
   //                         $('#ArticlesList').html(result);

   //                         $(".faSpinner").hide();
   //                     }
   //                 });
   //             },500)
   //         }
   //     }
   //});


    function ChangeUrl(page, url) {
        if (typeof (history.pushState) != "undefined") {
            var obj = { Page: page, Url: url };
            history.pushState(obj, obj.Page, obj.Url);
        } else {
            alert("Browser does not support HTML5.");
        }
    }

    function getUrlVars() {
        var vars = [], hash;
        var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
        for (var i = 0; i < hashes.length; i++) {
            hash = hashes[i].split('=');
            vars.push(hash[0]);
            vars[hash[0]] = hash[1];
        }
        return vars;
    }
</script>