LibraryApp/Areas/NewAdmin/Controllers/SolutionLibraryController.cs
using LibraryApp.Areas.NewAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryDataLayer;
using System.IO;
using Ionic.Zip;
using System.Text.RegularExpressions;
using LibraryBILayer.Admin;
using PagedList;

namespace LibraryApp.Areas.NewAdmin.Controllers
{
    public class SolutionLibraryController : Controller
    {
        // GET: Admin/SolutionLibrary
        AdminAuthentication adminAuthentication = new AdminAuthentication();
        public ActionResult Index()
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Panel");
            }
            //ViewBag.Subject = GetSolutionSubject();
            
                //ViewBag.University = GetUniversity();
            
            return View();
        }
        public ActionResult AddSolution()
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];
            if (objadmprof == null)
            {
                return RedirectToAction("Index", "Panel");
            }

            return View();
        }
        public static SelectList GetSolutionSubject()
        {
            SelectList ConList;
            using (var context = new XpertWebEntities())
            {
                var ObjMastersCat = (from c in context.tblSolutionSubjects
                                     select new 

                                     {
                                         SolSubID = c.SolSubID ?? Int32.MinValue,
                                         Subject = c.Subject
                                     }).ToList();
                ConList = new SelectList(ObjMastersCat, "SolSubID", "Subject");
                return ConList;
            }
        }
        public static SelectList GetUniversity(int UID)
        {
            SelectList ConList;
            using (var context = new XpertWebEntities())
            {
                var ObjMastersCat = (from c in context.tblUniversities
                                     join p in context.tblMainSubjects on c.UID equals p.UID
                                     where p.UID==UID
                                     select new
                                     {
                                         UID = c.UID,
                                         University = c.University
                                     }).ToList();
                ConList = new SelectList(ObjMastersCat, "UID", "University");
                return ConList;
            }
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult NewSolution(tblSolutionLibrary obj)
        {
            HttpCookie objadmprof = Request.Cookies["Admin"];

            int CheckStatus = Convert.ToInt32(Request.Form["CheckStatus"]);

            if(CheckStatus == 1)
            {
                obj.IsAnswer = true;
            }
            else
            {
                obj.IsAnswer = false;
            }
            int AnswerID = 0;
            int check = ManageLibrary.checkSolution(obj.Title);
            //ViewBag.Subject = GetSolutionSubject();
            //ViewBag.University = GetUniversity();
            //Guid guid = Guid.NewGuid();
            //string encoded = Convert.ToBase64String(guid.ToByteArray());
            //encoded = encoded
            //  .Replace("9/", "_")
            //  .Replace("+", "-");
            //string mainID = encoded.Substring(0, 7).ToUpper();
            string mainID = "SL" + DateTime.Now.ToString("yyyyMMdd") + "DO" + DateTime.Now.ToString("HHmmssfff");
           /*----GET ID----*/
           int getID = ManageLibrary.getSolID();

            if (check == 0)
            {
                //ViewBag.Subject = GetSolutionSubject();
                //ViewBag.University = GetUniversity();
                string path = "";
                string originalPath = System.Configuration.ConfigurationManager.AppSettings["SolutionPath"].ToString();
                string questionPath = System.Configuration.ConfigurationManager.AppSettings["QuestionPath"].ToString();
                string ZIppath = "";
                
                string subPath = "QS" + mainID + getID;
                if (Request.Files.Count > 0)
                {
                    for (int i = 0; i < Request.Files.Count; i++)
                    {
                        HttpPostedFileBase PostedFile = Request.Files[i];

                        string FileName = Path.GetFileName(PostedFile.FileName);

                        string FirstQuesName = FileName.Substring(0, 2);
                        string extension = Path.GetExtension(FileName);

                        if (FirstQuesName == "QU")
                        {
                            bool exists = System.IO.Directory.Exists(Server.MapPath(questionPath + subPath));

                            if (!exists)
                                System.IO.Directory.CreateDirectory(Server.MapPath(questionPath + subPath));

                            path = questionPath + subPath + "/" + "S" + i + mainID + getID + extension;

                            tblQuestionFile objQues = new tblQuestionFile();
                            objQues.CreatedBy = objadmprof["Email"];
                            objQues.CreatedOn = DateTime.Now;
                            objQues.Question_File_ID = subPath;
                            objQues.Question_File_Name = path;
                            objQues.IsActive = true;

                            ManageLibrary.AddQuestionFile(objQues);
                        }
                        else
                        {
                            path = originalPath + "S" + i + mainID + getID + extension;
                        }

                        PostedFile.SaveAs(Server.MapPath(path));
                        //i++;
                    }

                    /*-----MAKE ZIP FILE------*/
                    string modifiedPath = System.Configuration.ConfigurationManager.AppSettings["SolutionModifiedPath"].ToString();
                    string Orgpath = Server.MapPath(modifiedPath);//Location for inside Test Folder  
                    string mYpath = Server.MapPath(originalPath);

                    string[] Filenames = Directory.GetFiles(mYpath, "*" + getID + "*", SearchOption.AllDirectories);
                    using (ZipFile zip = new ZipFile())
                    {
                        zip.AddFiles(Filenames, "S" + mainID + getID.ToString());//Zip file inside filename  
                        zip.Save(Server.MapPath(modifiedPath + "S" + mainID + getID.ToString() + ".zip"));//location and name for creating zip file  
                    }

                    /*----DELETE FILES----*/
                    foreach (string filePath in Filenames)
                    {
                        System.IO.File.Delete(filePath);
                    }

                    ZIppath = modifiedPath + "S" + mainID + getID + ".zip";


                    if (obj.IsAnswer == true)
                    {
                        /*-----ADD ANSWER LIBRARY----*/
                        var ansObj = new tblAnswerLibrary();
                        //ansObj.FileName = FileName;
                        ansObj.FilePath = ZIppath;
                        ansObj.IsActive = true;
                        ManageLibrary.AddAnswer(ansObj);
                    }

                    /*----UPDATE ID----*/
                    ManageLibrary.updateSolID();

                    //int SolutionID = ManageLibrary.GetTopSolutionLibraryID();
                    //Regex re = new Regex("[;\\\\/:*?\"<>|&']");
                    if (obj.IsAnswer == true)
                    {
                        AnswerID = ManageLibrary.GetAnswerLibraryID();
                    }
                    //string meGet = Regex.Replace(obj.Title, "<.*?>", String.Empty);
                    //meGet = meGet.Replace(",", "").Replace(" ", "-").Replace("---", "-");
                    //System.Text.RegularExpressions.Regex rx = new System.Text.RegularExpressions.Regex("[^0-9a-zA-Z]+");
                    //meGet = rx.Replace(meGet, "-").ToLower().Substring(0, meGet.Length > 150 ? 150 : meGet.Length);

                    string meGet = Regex.Replace(obj.Title, "<.*?>", String.Empty);
                    //System.Text.RegularExpressions.Regex rx = new System.Text.RegularExpressions.Regex("[^0-9a-zA-Z]+");
                    string my_String = Regex.Replace(meGet, @"[^0-9a-zA-Z]+", " ");
                    meGet = my_String.Replace(" ", "-").ToLower().Substring(0, my_String.Length > 150 ? 150 : my_String.Length);

                    string meGet1 = Regex.Replace(ManageLibrary.GetUniversityName(Convert.ToInt32(obj.UID)), "<.*?>", String.Empty);
                    //System.Text.RegularExpressions.Regex rx1 = new System.Text.RegularExpressions.Regex("[^0-9a-zA-Z]+");
                    string my_String1 = Regex.Replace(meGet1, @"[^0-9a-zA-Z]+", " ");
                    meGet1 = my_String1.Replace(" ", "-").ToLower().Substring(0, my_String1.Length > 150 ? 150 : my_String1.Length);
                    //string getUrl = .ToLower().Substring(0, meGet.Length > 120 ? 120 : meGet.Length);

                    //string mURLText = getUrl.Replace(":", "").Replace(".", "").Replace(",", "").Replace(";", "").Replace(".", "").Replace("(", "").Replace(")", "").Replace("?", "").Replace("%", "percent").Replace("[", "").Replace("]", "").Replace("+", "").Replace("&", "").Replace("?", "");
                    /*---ADD SOLUTION LIBRARY----*/
                    var data = new tblSolutionLibrary();
                    data.SolSubID = obj.SolSubID;
                    data.AnswerID = AnswerID;
                    data.Title = obj.Title;
                    data.CreatedOn = DateTime.Now;
                    data.CreatedBy = objadmprof["Email"];

LibraryApp/Areas/NewAdmin/Views/SolutionLibrary/ViewSolution.cshtml
@using PagedList;
@using PagedList.Mvc
@{
    ViewBag.Title = "ListOfArticles";
    Layout = "~/Areas/NewAdmin/Views/Shared/_Layout.cshtml";
    var data = (PagedList<LibraryBILayer.Admin.SolutionLibr>)ViewBag.data;
}

<style>
    .pagination {
        float: right;
        margin: 0;
    }

        .pagination li.active a {
            cursor: not-allowed;
        }

            .pagination li.active a:hover {
                cursor: not-allowed;
            }

    .fa-sort {
        margin: 0 4px;
    }

    .faSpinner {
        display: none;
        position: absolute;
        z-index: 9;
        width: 100%;
        height: 100%;
        background: #ddd;
        opacity: 0.4;
    }

        .faSpinner i {
            position: absolute;
            left: 40%;
            top: 40%;
        }

    .myWd {
        width: 60%;
    }
</style>

<div class="content-wrapper" style="min-height: 960px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Manage Solution Library
            <div class="topAddNewLink"><a href="/NewAdmin/SolutionLibrary/AddSolution" class="btn btn-primary btn-xs">Add New</a></div>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Admin/Dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">View Solution Library</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Solution Library List</h3>

                        @*<a href="javascript:void(0)" class="btn btn-primary" onclick="window.history.back();" style="float: right;">Back</a>*@
                        <div class="checkbox">
                            <label>
                                <input style="float:right" type="checkbox" id="InActive" onchange="GetArticlesList(this);" class="minimal"> In-Active
                            </label>
                        </div>
                        <div class="box-tools pull-right">
                            <div class="has-feedback">
                                <input type="text" id="Search" class="form-control input-sm" placeholder="Search - Solution Library" style="width:300px" />
                                <span class="glyphicon glyphicon-search form-control-feedback"></span>
                            </div>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" id="ArticlesList">
                        @{
                            ViewDataDictionary extraData = new ViewDataDictionary(ViewData) { { "TotalArticleCount", ViewBag.TotalCount } };
                            Html.RenderPartial("_ListOfSolutionLibrary", data, extraData);
                        }

                    </div><!-- /.box-body -->
                </div>
                <!-- /.box-footer -->

            </div><!-- /.col -->
        </div>

    </section><!-- /.content -->
</div>

<script type="text/javascript">
    function DeleteRecord(Id, status) {
        var txt;
        var r = confirm("Do you really want to perform this action?");
        if (r == true) {
            $.ajax({
                url: '@Url.Action("DeleteSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                type: "POST",
                data: JSON.stringify({ Id: Id, status: status }),
                async: false,
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    if (result > 0) {
                        if (status == "0") {
                            toastr["success"]("Record is successfully deactivated.");
                        }
                        else if (status == "4") {
                            toastr["success"]("Record is successfully deleted.");
                        }
                        else {
                            toastr["success"]("Record is successfully activated.");
                        }
                        //  alert("Record is successfully deleted.");
                        GetArticlesList();
                    }
                    else {
                        toastr["error"]("Some error while processing your request.")
                    }
                },
                error: function (data) {
                    toastr["error"]("Some error while processing your request.")
                }
            });
        }
        else {
            txt = "You pressed Cancel!";
        }
    }

    function FinalDelete(Id, status) {
        var txt;
        var r = confirm("Do you really want to perform this action?");
        if (r == true) {
            $.ajax({
                url: '@Url.Action("FinalDeleteSolution", "SolutionLibrary", new { area = "NewAdmin" })',
                type: "POST",
                data: JSON.stringify({ Id: Id, status: status }),
                async: false,
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    if (result > 0) {
                        toastr["success"]("Record is successfully deleted.");
                        //  alert("Record is successfully deleted.");
                        GetArticlesList();
                    }
                    else {
                        toastr["error"]("Some error while processing your request.")
                    }
                },
                error: function (data) {
                    toastr["error"]("Some error while processing your request.")
                }
            });
        }
        else {
            txt = "You pressed Cancel!";
        }
    }
</script>
<script type="text/javascript">
    $('#Search').keyup(function () {
          var Search = $('#Search').val().replace(/[/\<>]/g, '');
          //alert("welcome");
        if ($('#Search').val().length > 2) {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                data: { SearchStr: Search, IsActive: 1 },
                success: function (data) {

                    if (data != 0) {
                        $('#ArticlesList').html(data)
                    }
                    else {
                        alert("No Record Found!!");
                    }
                },
                error: function (data) {
                }
            });
        }
        else {
            //var IsActive = false;
            $.ajax({
                type: 'GET',
                url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin" })',
                data: { SearchStr: "", IsActive: 1 },
                success: function (data) {

                    if (data != 0) {
                        $('#ArticlesList').html(data)
                    }
                    else {
                        alert("No Record Found!!");
                    }
                },
                error: function (data) {
                }
            });
        }
    });

</script>
<script>
    function GetArticlesList(elem) {
        $(elem).attr("disabled", 1);
        var HTML = "";
        var chkdata = "";
        var IsActive = $('#InActive').is(":Checked");
        if (IsActive == true)
        {
            chkdata = 0;
        }
        else
        {
            chkdata = 1;
        }
        $.ajax({
            type: 'GET',
            async: false,
            url: '@Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { @area = "NewAdmin" })',
            data: { IsActive: chkdata },
            success: function (data) {
                if (data != null) {
                    $('#ArticlesList').html(data)

                    $(elem).removeAttr("disabled");
                }
                else {
                    alert("No Record Found!!")
                }
            },
            error: function (response) {
            }
        });
    }

   // $('body').on('click', '#ArticlesList a', function (event) {
   //     if (!$(this).hasClass('btn-xs')) {
   //         var url = $(this).attr("href");
   //         var HTML = "";
   //         var InActive = $('#InActive').is(":Checked");
   //         $(".faSpinner").show();
   //         //alert("welcome home");
   //         if (url != undefined) {
   //             event.preventDefault();

   //             url = url + '&IsActive=' + $('#InActive').is(":Checked").toString();
   //             setTimeout(function () {
   //                 $.ajax({
   //                     url: url,
   //                     success: function (result) {
   //                         $('#ArticlesList').html(result);

   //                         $(".faSpinner").hide();
   //                     }
   //                 });
   //             },500)
   //         }
   //     }
   //});


    function ChangeUrl(page, url) {
        if (typeof (history.pushState) != "undefined") {
            var obj = { Page: page, Url: url };
            history.pushState(obj, obj.Page, obj.Url);
        } else {
            alert("Browser does not support HTML5.");
        }
    }

    function getUrlVars() {
        var vars = [], hash;
        var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
        for (var i = 0; i < hashes.length; i++) {
            hash = hashes[i].split('=');
            vars.push(hash[0]);
            vars[hash[0]] = hash[1];
        }
        return vars;
    }
</script>

LibraryApp/Areas/NewAdmin/Views/SolutionLibrary/_ListOfSolutionLibrary.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<LibraryBILayer.Admin.SolutionLibr>

@{
    var totalCount = Convert.ToInt32(ViewData["TotalArticleCount"]);
}
@if (Model.Count > 0 && Model != null)
{
    <table id="example1" class="table table-bordered table-striped" style=" display: block;overflow-x: auto;white-space: nowrap;">
        <thead>
            <tr>
                <th width="">ID</th>
                <th width="">Created On</th>
                <th width="">University</th>
                <th width="">Subject</th>
                <th width="">Subject Name</th>
                <th width="">Country</th>
                <th width="">Code</th>

                <th width="">Amount</th>
                <th width="">Status</th>
                <th width="50px">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Sol_ID</td>
                <td>@Convert.ToDateTime(item.CreatedOn).ToString("yyyy-MM-dd")</td>
                <td>@item.university</td>
                <td>@item.Subject</td>
                <td>@item.SubjectName</td>
                <td>@item.country</td>
                <td>@item.SubjectCode</td>

                <td>@item.Amount</td>
                <td>@(item.Status == true ? "Active" : "Not Active")</td>
                <td>

                    @if (item.Status == true)
                    {
                        <a title="Edit" href="@Url.Action("EditSolutionLibrary", "SolutionLibrary", new { @area = "NewAdmin", @Id = item.Sol_ID })"><i class="fa  fa-edit fa-2x"></i></a>
                        <a title="Deactivate" onclick="return DeleteRecord(@item.Sol_ID, 0)"><i class="fa fa-times-circle fa-2x"></i></a>
                        <a title="Delete" onclick="return FinalDelete(@item.Sol_ID, 0)"><i class="fa fa-trash fa-2x"></i></a>

                    }
                    else
                    {
                        <a title="Activate" onclick="return DeleteRecord(@item.Sol_ID, 1)"><i class="fa fa-check-circle fa-2x"></i></a>

                    }
                </td>
            </tr>
            }
        </tbody>

    </table>
    if (totalCount > ViewBag.pageSize)
    {
        @Html.PagedListPager(Model, page => Url.Action("_ListOfSolutionLibrary", "SolutionLibrary", new { area = "NewAdmin", IsActive = ViewBag.IsDeleted, page }));
    }
}
else
{
    <span style="color:rosybrown"><strong>No record found!!</strong></span>
}